project:
  type: website
  output-dir: docs

website:
  title: "Miranda's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
      - Projects.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    toc-location: left
    body-bg: "#6a8c95"
    body-color: "#2350dc"
    linkcolor: "#2fc5d0"

editor: visual

