project:
  type: website
  output-dir: docs

website:
  title: "Miranda's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
      - Projects.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    toc-location: left
    linkcolor: "#2542da"

editor: visual

