---
title: "CV"
format: html
---

# Resume/CV

Miranda Chin

mchin2387\@gmail.com • 720-469-2539 • www.linkedin.com/in/chin-miranda

### <b>ENVIRONMENTAL PROFILE SUMMARY</b>

I am a current student interested in both technical and field experience in a workplace centered around environmental science. I have knowledge in the biological sciences as well as data analytics and have experience working independently and as part of a team.

▪ Strong understanding of biological and environmental based sciences

▪ Adaptable and able to use multiple software programs in various applications

▪ Committed to helping others and giving back to local communities

------------------------------------------------------------------------

### <b>ECOSYSTEM SCIENCE EDUCATION</b>

B.S. in Ecosystem Science and Sustainability Degree expected May 2025

Colorado State University, Fort Collins, CO GPA: 3.8

------------------------------------------------------------------------

### <b>NATURAL RESOURCES AND RELATED COURSEWORK</b>

<i>SUPER Program, Undergraduate Ecological Research Fall 2024-Present</i>

▪ Developed skills in data analysis for remote sensing work

▪ Bolstered statistical skills in programs such as R

<i>Writing in the Disciplines: Science, CO 301B Summer 2023</i>

▪ Developed the ability to write clearly and concisely with a focus in the sciences

▪ Able to research different topics and analyze academic papers efficiently

<i>Ecology, LIFE 320 Spring 2024</i>

▪ Deepened my understanding of concepts in both biology and ecology

▪ Established knowledge of systems thinking and natural resources

<i>Limnology, ESS 474 Fall 2024</i>

▪ Utilized skills in R to analyze data collected from field work

▪ Utilized knowledge of biological systems to critically solve problems

------------------------------------------------------------------------

### <b>SOCIAL JUSTICE AND COMMUNITY EXPERIENCE</b>

<i>Mentor for Key Communities August 2024-May 2025</i>

Colorado State University, Fort Collins

▪ Kept track of students’ academics and provided aid if necessary

▪ Engaged with students both in and out of a classroom setting

▪ Organized large group events and kept track of logistics

<i>Volunteer at FoCo Cafe October 2023-April 2024</i>

FoCo Café, Fort Collins

▪ Dedicated to giving back to the community and helping those in need

▪ Greeted customers and those seeking food assistance

▪ Responsible for picking up tasks and carrying out a variety of work
